/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.developer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class IdentificadorDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1767177943918293684L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IdentificadorDto\",\"namespace\":\"io.confluent.developer\",\"fields\":[{\"name\":\"idIdent\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"idEcGrupo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"tipoIdent\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"dataAlteracao\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"placa\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"ativo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"bloqTemp\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"bloqSaldo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<IdentificadorDto> ENCODER =
      new BinaryMessageEncoder<IdentificadorDto>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<IdentificadorDto> DECODER =
      new BinaryMessageDecoder<IdentificadorDto>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<IdentificadorDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<IdentificadorDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<IdentificadorDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<IdentificadorDto>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this IdentificadorDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a IdentificadorDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a IdentificadorDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static IdentificadorDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String idIdent;
   private java.lang.String idEcGrupo;
   private java.lang.String tipoIdent;
   private java.lang.String dataAlteracao;
   private java.lang.String placa;
   private java.lang.String ativo;
   private java.lang.String bloqTemp;
   private java.lang.String bloqSaldo;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public IdentificadorDto() {}

  /**
   * All-args constructor.
   * @param idIdent The new value for idIdent
   * @param idEcGrupo The new value for idEcGrupo
   * @param tipoIdent The new value for tipoIdent
   * @param dataAlteracao The new value for dataAlteracao
   * @param placa The new value for placa
   * @param ativo The new value for ativo
   * @param bloqTemp The new value for bloqTemp
   * @param bloqSaldo The new value for bloqSaldo
   */
  public IdentificadorDto(java.lang.String idIdent, java.lang.String idEcGrupo, java.lang.String tipoIdent, java.lang.String dataAlteracao, java.lang.String placa, java.lang.String ativo, java.lang.String bloqTemp, java.lang.String bloqSaldo) {
    this.idIdent = idIdent;
    this.idEcGrupo = idEcGrupo;
    this.tipoIdent = tipoIdent;
    this.dataAlteracao = dataAlteracao;
    this.placa = placa;
    this.ativo = ativo;
    this.bloqTemp = bloqTemp;
    this.bloqSaldo = bloqSaldo;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return idIdent;
    case 1: return idEcGrupo;
    case 2: return tipoIdent;
    case 3: return dataAlteracao;
    case 4: return placa;
    case 5: return ativo;
    case 6: return bloqTemp;
    case 7: return bloqSaldo;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: idIdent = value$ != null ? value$.toString() : null; break;
    case 1: idEcGrupo = value$ != null ? value$.toString() : null; break;
    case 2: tipoIdent = value$ != null ? value$.toString() : null; break;
    case 3: dataAlteracao = value$ != null ? value$.toString() : null; break;
    case 4: placa = value$ != null ? value$.toString() : null; break;
    case 5: ativo = value$ != null ? value$.toString() : null; break;
    case 6: bloqTemp = value$ != null ? value$.toString() : null; break;
    case 7: bloqSaldo = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'idIdent' field.
   * @return The value of the 'idIdent' field.
   */
  public java.lang.String getIdIdent() {
    return idIdent;
  }


  /**
   * Sets the value of the 'idIdent' field.
   * @param value the value to set.
   */
  public void setIdIdent(java.lang.String value) {
    this.idIdent = value;
  }

  /**
   * Gets the value of the 'idEcGrupo' field.
   * @return The value of the 'idEcGrupo' field.
   */
  public java.lang.String getIdEcGrupo() {
    return idEcGrupo;
  }


  /**
   * Sets the value of the 'idEcGrupo' field.
   * @param value the value to set.
   */
  public void setIdEcGrupo(java.lang.String value) {
    this.idEcGrupo = value;
  }

  /**
   * Gets the value of the 'tipoIdent' field.
   * @return The value of the 'tipoIdent' field.
   */
  public java.lang.String getTipoIdent() {
    return tipoIdent;
  }


  /**
   * Sets the value of the 'tipoIdent' field.
   * @param value the value to set.
   */
  public void setTipoIdent(java.lang.String value) {
    this.tipoIdent = value;
  }

  /**
   * Gets the value of the 'dataAlteracao' field.
   * @return The value of the 'dataAlteracao' field.
   */
  public java.lang.String getDataAlteracao() {
    return dataAlteracao;
  }


  /**
   * Sets the value of the 'dataAlteracao' field.
   * @param value the value to set.
   */
  public void setDataAlteracao(java.lang.String value) {
    this.dataAlteracao = value;
  }

  /**
   * Gets the value of the 'placa' field.
   * @return The value of the 'placa' field.
   */
  public java.lang.String getPlaca() {
    return placa;
  }


  /**
   * Sets the value of the 'placa' field.
   * @param value the value to set.
   */
  public void setPlaca(java.lang.String value) {
    this.placa = value;
  }

  /**
   * Gets the value of the 'ativo' field.
   * @return The value of the 'ativo' field.
   */
  public java.lang.String getAtivo() {
    return ativo;
  }


  /**
   * Sets the value of the 'ativo' field.
   * @param value the value to set.
   */
  public void setAtivo(java.lang.String value) {
    this.ativo = value;
  }

  /**
   * Gets the value of the 'bloqTemp' field.
   * @return The value of the 'bloqTemp' field.
   */
  public java.lang.String getBloqTemp() {
    return bloqTemp;
  }


  /**
   * Sets the value of the 'bloqTemp' field.
   * @param value the value to set.
   */
  public void setBloqTemp(java.lang.String value) {
    this.bloqTemp = value;
  }

  /**
   * Gets the value of the 'bloqSaldo' field.
   * @return The value of the 'bloqSaldo' field.
   */
  public java.lang.String getBloqSaldo() {
    return bloqSaldo;
  }


  /**
   * Sets the value of the 'bloqSaldo' field.
   * @param value the value to set.
   */
  public void setBloqSaldo(java.lang.String value) {
    this.bloqSaldo = value;
  }

  /**
   * Creates a new IdentificadorDto RecordBuilder.
   * @return A new IdentificadorDto RecordBuilder
   */
  public static io.confluent.developer.IdentificadorDto.Builder newBuilder() {
    return new io.confluent.developer.IdentificadorDto.Builder();
  }

  /**
   * Creates a new IdentificadorDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new IdentificadorDto RecordBuilder
   */
  public static io.confluent.developer.IdentificadorDto.Builder newBuilder(io.confluent.developer.IdentificadorDto.Builder other) {
    if (other == null) {
      return new io.confluent.developer.IdentificadorDto.Builder();
    } else {
      return new io.confluent.developer.IdentificadorDto.Builder(other);
    }
  }

  /**
   * Creates a new IdentificadorDto RecordBuilder by copying an existing IdentificadorDto instance.
   * @param other The existing instance to copy.
   * @return A new IdentificadorDto RecordBuilder
   */
  public static io.confluent.developer.IdentificadorDto.Builder newBuilder(io.confluent.developer.IdentificadorDto other) {
    if (other == null) {
      return new io.confluent.developer.IdentificadorDto.Builder();
    } else {
      return new io.confluent.developer.IdentificadorDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for IdentificadorDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IdentificadorDto>
    implements org.apache.avro.data.RecordBuilder<IdentificadorDto> {

    private java.lang.String idIdent;
    private java.lang.String idEcGrupo;
    private java.lang.String tipoIdent;
    private java.lang.String dataAlteracao;
    private java.lang.String placa;
    private java.lang.String ativo;
    private java.lang.String bloqTemp;
    private java.lang.String bloqSaldo;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.developer.IdentificadorDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.idIdent)) {
        this.idIdent = data().deepCopy(fields()[0].schema(), other.idIdent);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.idEcGrupo)) {
        this.idEcGrupo = data().deepCopy(fields()[1].schema(), other.idEcGrupo);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.tipoIdent)) {
        this.tipoIdent = data().deepCopy(fields()[2].schema(), other.tipoIdent);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.dataAlteracao)) {
        this.dataAlteracao = data().deepCopy(fields()[3].schema(), other.dataAlteracao);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.placa)) {
        this.placa = data().deepCopy(fields()[4].schema(), other.placa);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.ativo)) {
        this.ativo = data().deepCopy(fields()[5].schema(), other.ativo);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.bloqTemp)) {
        this.bloqTemp = data().deepCopy(fields()[6].schema(), other.bloqTemp);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.bloqSaldo)) {
        this.bloqSaldo = data().deepCopy(fields()[7].schema(), other.bloqSaldo);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing IdentificadorDto instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.developer.IdentificadorDto other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.idIdent)) {
        this.idIdent = data().deepCopy(fields()[0].schema(), other.idIdent);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.idEcGrupo)) {
        this.idEcGrupo = data().deepCopy(fields()[1].schema(), other.idEcGrupo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tipoIdent)) {
        this.tipoIdent = data().deepCopy(fields()[2].schema(), other.tipoIdent);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dataAlteracao)) {
        this.dataAlteracao = data().deepCopy(fields()[3].schema(), other.dataAlteracao);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.placa)) {
        this.placa = data().deepCopy(fields()[4].schema(), other.placa);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ativo)) {
        this.ativo = data().deepCopy(fields()[5].schema(), other.ativo);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.bloqTemp)) {
        this.bloqTemp = data().deepCopy(fields()[6].schema(), other.bloqTemp);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.bloqSaldo)) {
        this.bloqSaldo = data().deepCopy(fields()[7].schema(), other.bloqSaldo);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'idIdent' field.
      * @return The value.
      */
    public java.lang.String getIdIdent() {
      return idIdent;
    }


    /**
      * Sets the value of the 'idIdent' field.
      * @param value The value of 'idIdent'.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder setIdIdent(java.lang.String value) {
      validate(fields()[0], value);
      this.idIdent = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'idIdent' field has been set.
      * @return True if the 'idIdent' field has been set, false otherwise.
      */
    public boolean hasIdIdent() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'idIdent' field.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder clearIdIdent() {
      idIdent = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'idEcGrupo' field.
      * @return The value.
      */
    public java.lang.String getIdEcGrupo() {
      return idEcGrupo;
    }


    /**
      * Sets the value of the 'idEcGrupo' field.
      * @param value The value of 'idEcGrupo'.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder setIdEcGrupo(java.lang.String value) {
      validate(fields()[1], value);
      this.idEcGrupo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'idEcGrupo' field has been set.
      * @return True if the 'idEcGrupo' field has been set, false otherwise.
      */
    public boolean hasIdEcGrupo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'idEcGrupo' field.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder clearIdEcGrupo() {
      idEcGrupo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'tipoIdent' field.
      * @return The value.
      */
    public java.lang.String getTipoIdent() {
      return tipoIdent;
    }


    /**
      * Sets the value of the 'tipoIdent' field.
      * @param value The value of 'tipoIdent'.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder setTipoIdent(java.lang.String value) {
      validate(fields()[2], value);
      this.tipoIdent = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'tipoIdent' field has been set.
      * @return True if the 'tipoIdent' field has been set, false otherwise.
      */
    public boolean hasTipoIdent() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'tipoIdent' field.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder clearTipoIdent() {
      tipoIdent = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'dataAlteracao' field.
      * @return The value.
      */
    public java.lang.String getDataAlteracao() {
      return dataAlteracao;
    }


    /**
      * Sets the value of the 'dataAlteracao' field.
      * @param value The value of 'dataAlteracao'.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder setDataAlteracao(java.lang.String value) {
      validate(fields()[3], value);
      this.dataAlteracao = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'dataAlteracao' field has been set.
      * @return True if the 'dataAlteracao' field has been set, false otherwise.
      */
    public boolean hasDataAlteracao() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'dataAlteracao' field.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder clearDataAlteracao() {
      dataAlteracao = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'placa' field.
      * @return The value.
      */
    public java.lang.String getPlaca() {
      return placa;
    }


    /**
      * Sets the value of the 'placa' field.
      * @param value The value of 'placa'.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder setPlaca(java.lang.String value) {
      validate(fields()[4], value);
      this.placa = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'placa' field has been set.
      * @return True if the 'placa' field has been set, false otherwise.
      */
    public boolean hasPlaca() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'placa' field.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder clearPlaca() {
      placa = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'ativo' field.
      * @return The value.
      */
    public java.lang.String getAtivo() {
      return ativo;
    }


    /**
      * Sets the value of the 'ativo' field.
      * @param value The value of 'ativo'.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder setAtivo(java.lang.String value) {
      validate(fields()[5], value);
      this.ativo = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'ativo' field has been set.
      * @return True if the 'ativo' field has been set, false otherwise.
      */
    public boolean hasAtivo() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'ativo' field.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder clearAtivo() {
      ativo = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'bloqTemp' field.
      * @return The value.
      */
    public java.lang.String getBloqTemp() {
      return bloqTemp;
    }


    /**
      * Sets the value of the 'bloqTemp' field.
      * @param value The value of 'bloqTemp'.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder setBloqTemp(java.lang.String value) {
      validate(fields()[6], value);
      this.bloqTemp = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'bloqTemp' field has been set.
      * @return True if the 'bloqTemp' field has been set, false otherwise.
      */
    public boolean hasBloqTemp() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'bloqTemp' field.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder clearBloqTemp() {
      bloqTemp = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'bloqSaldo' field.
      * @return The value.
      */
    public java.lang.String getBloqSaldo() {
      return bloqSaldo;
    }


    /**
      * Sets the value of the 'bloqSaldo' field.
      * @param value The value of 'bloqSaldo'.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder setBloqSaldo(java.lang.String value) {
      validate(fields()[7], value);
      this.bloqSaldo = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'bloqSaldo' field has been set.
      * @return True if the 'bloqSaldo' field has been set, false otherwise.
      */
    public boolean hasBloqSaldo() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'bloqSaldo' field.
      * @return This builder.
      */
    public io.confluent.developer.IdentificadorDto.Builder clearBloqSaldo() {
      bloqSaldo = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IdentificadorDto build() {
      try {
        IdentificadorDto record = new IdentificadorDto();
        record.idIdent = fieldSetFlags()[0] ? this.idIdent : (java.lang.String) defaultValue(fields()[0]);
        record.idEcGrupo = fieldSetFlags()[1] ? this.idEcGrupo : (java.lang.String) defaultValue(fields()[1]);
        record.tipoIdent = fieldSetFlags()[2] ? this.tipoIdent : (java.lang.String) defaultValue(fields()[2]);
        record.dataAlteracao = fieldSetFlags()[3] ? this.dataAlteracao : (java.lang.String) defaultValue(fields()[3]);
        record.placa = fieldSetFlags()[4] ? this.placa : (java.lang.String) defaultValue(fields()[4]);
        record.ativo = fieldSetFlags()[5] ? this.ativo : (java.lang.String) defaultValue(fields()[5]);
        record.bloqTemp = fieldSetFlags()[6] ? this.bloqTemp : (java.lang.String) defaultValue(fields()[6]);
        record.bloqSaldo = fieldSetFlags()[7] ? this.bloqSaldo : (java.lang.String) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IdentificadorDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<IdentificadorDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IdentificadorDto>
    READER$ = (org.apache.avro.io.DatumReader<IdentificadorDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.idIdent);

    out.writeString(this.idEcGrupo);

    out.writeString(this.tipoIdent);

    out.writeString(this.dataAlteracao);

    out.writeString(this.placa);

    out.writeString(this.ativo);

    out.writeString(this.bloqTemp);

    out.writeString(this.bloqSaldo);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.idIdent = in.readString();

      this.idEcGrupo = in.readString();

      this.tipoIdent = in.readString();

      this.dataAlteracao = in.readString();

      this.placa = in.readString();

      this.ativo = in.readString();

      this.bloqTemp = in.readString();

      this.bloqSaldo = in.readString();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.idIdent = in.readString();
          break;

        case 1:
          this.idEcGrupo = in.readString();
          break;

        case 2:
          this.tipoIdent = in.readString();
          break;

        case 3:
          this.dataAlteracao = in.readString();
          break;

        case 4:
          this.placa = in.readString();
          break;

        case 5:
          this.ativo = in.readString();
          break;

        case 6:
          this.bloqTemp = in.readString();
          break;

        case 7:
          this.bloqSaldo = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










